### ISSUE TITLE
5 Sensibo create Savant pro App  scenes issues

### ISSUE THREAD

**Issue by Pong168** [caboose014/SensiboSkySavantProfile#1]
Dear 

Hi, i am new junior savant installer, now i have some problem for sensibo savant control, since now i have the project the house is use 5 sensibo device for control 5 air-con unit,  is can independent control of each device, but for example : if in savant pro app create the one scenes for all off/all on the 5 Air-con, is can't not working in the scenes, or create scenes same time control 2 sensibo ,now can i fix this issues ? or can i help me ? many thanks

Regards

ftrpong

**Comment by caboose014** [comment]
If you are able to control single units with no issues then it sounds more like a problem in savants scene controls.

I suggest you raise this with Savant
